### ISSUE TITLE
Copyright violation notice

### ISSUE THREAD

**Issue by sinus-x** [strawberry-py/strawberry-py#87]
We have found out this repository is breaching the GNU General Public License v3.0 (further as License) the code was released under.

While the License allows and encourages code modification and sharing, it must be done so with proper credit. It seems the source code has been altered to completely remove the names of original authors and original project. While the project's README mentions "several amazing contributors", it is only providing a link to GitHub Contributors page, which is not shipped with the software and is not sufficient to follow the terms of the License. This is only amplified after opening the Contributors page, which shows that the contributions to the original project are the vast majority of the code.

We are requesting you to comply with the terms of the License and properly disclose the name of the original project and names of the original contributors that have authored it, in such a way to be compliant with the terms.

Failure to correct the violation will trigger the Section 8 of the License, terminating all the rights you have over the software. The correction must be done in the time spans defined by the License.

**Comment by ArcasCZ** [comment]
This problem was addressed in PR #88. 

The mention of the original project is now a hyperlink to the GitHub repository.
The original authors were previously mentioned as maintainers, which of course I've altered as they are not maintaining this repo and is completely compliant with GNU GPL v3. However, I've added their mention into the README.md as well.

Regarding the source code, there was no mention of the original authors, not even in the license file.

As far as I'm concern the current state of the repository is compliant with the license, therefor I'm closing this issue. If you feel like you are not satisfied with the changes, feel free to propose how the issue should be corrected to satisfy your need for credits.
